# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: pg_db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: lv_blog
      POSTGRES_INITDB_ARGS: "-A md5"
    volumes:
      - /var/www/html/test.com/postgres/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
